# Generated by Django 2.2 on 2020-12-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201228_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_path',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
