# Generated by Django 2.2 on 2020-12-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('web_page', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Welcome',
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
