# Generated by Django 2.2 on 2020-12-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20201229_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_page', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='General',
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
