# Generated by Django 2.2 on 2020-12-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20201229_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_path',
            field=models.FileField(blank=True, default='default/default.jpg', null=True, upload_to='photos'),
        ),
    ]
