# Generated by Django 2.2 on 2020-12-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20201229_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_path',
            field=models.FileField(blank=True, default='default/default.jpg', null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image_path',
            field=models.FileField(blank=True, default='default/icons.jpg', null=True, upload_to='icons/%Y/%m/%d'),
        ),
    ]
