# Generated by Django 2.2 on 2020-12-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image_path',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
