# Generated by Django 2.2 on 2020-12-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20201229_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon_name',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Icon'),
        ),
    ]
