# Generated by Django 2.2 on 2020-12-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20201230_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
