# Generated by Django 2.2 on 2021-01-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210127_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='description',
            field=models.TextField(),
        ),
    ]
