# Generated by Django 2.2 on 2021-01-29 13:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20210127_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
