# Generated by Django 2.2 on 2021-01-29 18:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20210129_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
