FROM nginx:1.19.0-alpine

COPY ./default.conf /etc/nginx/conf.d/default.conf
#COPY ./default.conf /etc/nginx/sites-enabled/portfolio.conf

# COPY ./django_gunicorn.conf /etc/nginx/conf.d/django_gunicorn.conf